name: Format code

on:
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Specify the Python version you need

      - name: Install dependencies
        run: |
          pip install black isort autoflake

      - name: Format code with black
        run: black .

      - name: Sort imports with isort
        run: isort .

      - name: Remove unused imports with autoflake
        run: autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive .

      - name: Commit changes
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "Format code with black"
